image: Visual Studio 2022
configuration: Release

before_build:
    - cmd: nuget restore

    - ps: Start-FileDownload "https://www.autodesk.com/content/dam/autodesk/www/adn/fbx/2020-2-1/fbx202021_fbxsdk_vs2019_win.exe" -FileName "FBX.exe"
    - ps: Start-Process -Wait "FBX.exe" "/S /D=$($env:APPVEYOR_BUILD_FOLDER)\MikuMikuLibrary.Native\Dependencies\FBX"

build:
    project: MikuMikuLibrary.sln
    
after_build:
    - publish.bat

artifacts:
    - path: publish/MikuMikuLibrary-x64.7z
      name: X64
    - path: publish/MikuMikuLibrary-x86.7z
      name: X86